version: '3.3'

services: 
  app_csrf:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000
    image: app_csrf_1
    network_mode: bridge
    stdin_open: true
    tty: true
volumes: 
  db-config:
  db-data:
