version: '3.3'

services: 
  app_object_injection:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - 80
    image: app_object_injection
    stdin_open: true
    tty: true
    network_mode: bridge
volumes: 
  db-config:
  db-data:  
