version: '3.3'

services: 
  app-cmdi:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - 8000
    image: cmdi
    stdin_open: true
    tty: true
volumes: 
  db-config:
  db-data:  
