version: '3.3'
services: 
  app_stored_xss:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - 3000
    image: stored_xss
    network_mode: bridge
    stdin_open: true
    tty: true
volumes: 
  db-config:
  db-data:
