version: '3.3'

services: 
  db_ssti:
    image: mariadb
    restart: always 
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    ports:
      - $DB_DOCKER_PORT
    volumes: 
      - .:/docker-entrypoint-initdb.d
  app_ssti:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:
      DB_HOST: mariadb
    ports:
      - 8080
    image: app_ssti
    depends_on:
      - mariadb
    stdin_open: true
    tty: true
volumes: 
  db-config:
  db-data:

networks:
  default:
    external:
      name: my-bridge-network