version: '3.3'

services: 
  db_sqli:
    image: mariadb
    restart: always 
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes: 
      - ./sql.sql:/docker-entrypoint-initdb.d/sql.sql
  app_sqli:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:
      DB_HOST: db_sqli
    ports:
      - 80
    image: app_sqli
    depends_on:
      - db_sqli
    stdin_open: true
    tty: true
volumes: 
  db-config:
  db-data:  
  
networks:
  default:
    external:
      name: my-bridge-network