version: '3.3'

services: 
  db_sqli:
    image: mariadb
    restart: always 
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes: 
      - ./sql.sql:/docker-entrypoint-initdb.d/sql.sql
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  app_sqli:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:
      DB_HOST: db_sqli
    ports:
      - 80
    image: sqli_1_app
    depends_on:
      - db_sqli
    stdin_open: true
    tty: true
    volumes: 
      - .:/var/www/html
volumes: 
  db-config:
  db-data:  
