version: '3.3'

services: 
  app_rxss:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - 3000
    image: app_rxss_1
    stdin_open: true
    tty: true
    volumes: 
      - .:/app/
      - /app/node_modules
volumes: 
  db-config:
  db-data:
