version: '3.3'

services: 
  app_rxss:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - 3000
    image: app_rxss
    stdin_open: true
    tty: true
    network_mode: bridge
volumes: 
  db-config:
  db-data:
