version: '3.3'

services: 
  app_fileupload:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - 80
    image: fileupload_app_1
    stdin_open: true
    tty: true
    network_mode: bridge
volumes: 
  db-config:
  db-data:  
